### ISSUE TITLE
Cliff corners need to be 'smoothed out'

### ISSUE THREAD

**Issue by andrewphamvk** [KonradJanica/CG_Assign3#1]
![cliffcorner](https://cloud.githubusercontent.com/assets/7805458/7512667/ac8e734c-f4ed-11e4-9fcb-41bf98a79956.png)

**Comment by KonradJanica** [comment]
I̶ ̶t̶h̶i̶n̶k̶ ̶m̶o̶r̶e̶ ̶i̶m̶p̶o̶r̶t̶a̶n̶t̶l̶y̶ ̶w̶e̶ ̶g̶o̶t̶ ̶t̶o̶ ̶f̶i̶n̶d̶ ̶a̶ ̶w̶a̶y̶ ̶t̶o̶ ̶t̶u̶r̶n̶ ̶t̶h̶e̶ ̶r̶o̶a̶d̶ ̶a̶l̶o̶n̶g̶ ̶t̶h̶e̶ ̶t̶u̶r̶n̶e̶d̶ ̶t̶e̶r̶r̶a̶i̶n̶.̶ ̶  

Cliffs still need to be smoothed but roads now turn with the terrain. Another issue which is low priority is allowing to change angle degree of road. Currently the terrain/road is always relatively on the same X plane, however changing this might cause problems with collisions and later joining terrain/road tiles.
-Konrad
