### ISSUE TITLE
Normal Calculation

### ISSUE THREAD

**Issue by mitchanderso** [KonradJanica/CG_Assign3#7]
Hey guys, I propose we move normal calculation into the vertex shader possibly because if we are to have animation (for the water) the vertices change positions so doing static CPU side normal calculations is not good enough, this could be done by having a new shader just for water

open to any ideas!

**Comment by mitchanderso** [comment]
n.b This is quite important otherwise lighting on the water will look atrocious

**Comment by KonradJanica** [comment]
I second doing it in the shader. I'm sure there's a super optimal way of doing it by just changing the normals at parts of the sine/cosine wave but for simplicity sake just try to do the cross product code in the shader (by passing in the vertices neighbours? not sure)
