### ISSUE TITLE
Camera Zooming is broken in "car_is_camera" branch

### ISSUE THREAD

**Issue by KonradJanica** [KonradJanica/CG_Assign3#9]
I think the easiest and a very optimal way of making the car move is to attach it to the camera. I have done this in the car_is_camera branch.

However, if you test it for yourself you will see the controls are originating around the camera position and not the car itself. 

For some reason attaching the car model to the camera has broken the zoom. If we fix this, we could position the camera in the car and zoom out, this method of car movement would work very well.

The only change needed to attach the car is in renderer.cc -> Render(Object \* ... instead of translating the camera_matrix by the view matrix, we leave it in camera space. See the if statement with a search for "camera_matrix"

**Comment by KonradJanica** [comment]
Actually don't waste time with this unless we actually need zoom. The effect won't work with what I'm thinking and instead we will get a fish bowl affect that we don't want

**Comment by mitchanderso** [comment]
Idk if replying to this email works but I think we want movement separate
to camera, I have gotten sahils driving game code and I think we can try
and work from there

**Comment by KonradJanica** [comment]
Yeah replying works, that's pretty handy to know. Love Github!

Package and attach it to the facebook group ASAP. I'm really stuck on how to change local position of object into global space in the world. I know of a really crude way of doing it but I couldn't figure out how to translate the object's position to the road's position for collision detection.

**Comment by mitchanderso** [comment]
i think we can close this?

**Comment by KonradJanica** [comment]
yeah, definitely. There is no reason at all to do car is camera, it's too inflexible especially with clipping through the cliff on turning.
